repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: pnpm prettier
        language: system
        types: [file]
        types_or:
          [javascript, jsx, ts, tsx, json, css, scss, html, markdown, yaml]
        pass_filenames: false

      - id: eslint
        name: eslint
        entry: pnpm lint
        language: system
        types: [file]
        types_or: [javascript, jsx, ts, tsx]
        pass_filenames: false

      - id: typescript
        name: typescript
        entry: pnpm type-check
        language: system
        types: [file]
        types_or: [ts, tsx]
        pass_filenames: false
